# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_image_slide_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievments_image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(default=' ', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='crew_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='crew_sir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sir_img', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(default=' ', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='our_ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_ride_image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(default=' ', max_length=1024)),
            ],
        ),
    ]
