# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_achievments_crew_members_crew_sir_our_ride'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='achievments',
            new_name='achievment',
        ),
    ]
