# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170605_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='crew_members',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='crew_sir',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='image_slide',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='our_ride',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
    ]
