# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170606_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='achievments_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='crew_sir',
            name='sir_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_slide',
            name='slide_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='our_ride',
            name='our_ride_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
