# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170606_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_slide',
            old_name='title',
            new_name='caption',
        ),
    ]
