# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew_sir',
            name='text_1',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AddField(
            model_name='crew_sir',
            name='text_2',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
        migrations.AddField(
            model_name='crew_sir',
            name='text_3',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
    ]
