# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20170606_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievments_image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, default=' ', max_length=1024)),
                ('content', models.TextField(blank=True, default=' ', max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='achievment',
        ),
    ]
