# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_achievement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='links',
            field=models.CharField(blank=True, default=' ', max_length=1024),
        ),
    ]
