# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_partners_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=' ', max_length=1024)),
                ('address', models.CharField(blank=True, default=' ', max_length=1024)),
                ('email', models.CharField(blank=True, default=' ', max_length=1024)),
            ],
        ),
    ]
